# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0002_auto_20171020_2047'),
        ('coriandrum', '0002_auto_20171020_2001'),
    ]

    operations = [
    ]
