# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0004_merge_20171020_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='coriandrumuser',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
