# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0007_coriandrumuser_raw_vk_user_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('new', 'Новый пост'), ('in_consideration', 'Заблокирован редактором на осознание'), ('looks_interesting', 'Понравился редактору'), ('trash', 'В топке'), ('published', 'Опубликован')], default='new', max_length=25),
        ),
    ]
