# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0009_postattachment'),
        ('coriandrum', '0006_auto_20171021_1015'),
    ]

    operations = [
    ]
