# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0010_merge_20171021_1557'),
        ('coriandrum', '0010_remove_coriandrumuser_level'),
    ]

    operations = [
    ]
