# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:08
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0012_auto_20171021_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='raw_vk_attachments_payload',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='coriandrumuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('new', 'Новый пост'), ('in_consideration', 'Заблокирован редактором на осознание'), ('looks_interesting', 'Понравился редактору'), ('trash', 'В топке'), ('published', 'Опубликован')], default='new', max_length=25),
        ),
    ]
