# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0013_auto_20171021_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
