# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coriandrum', '0015_auto_20171021_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='raw_vk_attachments_payload',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
